apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-dev
spec:
  selector:
    matchLabels:
      stage: dev
  type: ClusterIp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetport: {{ .Values.containerport }}
  - name: https
    protocol: TCP
    port: 443
    targetport: 443
